before_script:
   - apt-get update -qq
   - apt-get install openjdk-14-jdk ant junit


build_program:
    stage: build
    script: 
        - javac src/Main.java

test_program:
    stage: test
    script:
        -ant compile-test   
        -ant test