image: ubuntu:20.04

before_script:
   - apt-get update -qq
   - apt-get install -yqq openjdk-14-jdk ant junit


build_program:
    stage: build
    script: 
        - javac --release 14 -encoding utf8 -cp junit-4.12.jar:src/ testGame.java

test_program:
    stage: test
    script:
        - java -cp .:junit-4.12.jar:hamcrest-core-1.3.jar:src/ org.junit.runner.JUnitCore testGame