image: ubuntu:20.04

before_script:
    - apt-get update -qq
    - apt-get install -yqq openjdk-14-jdk ant junit


build_and_do_unit_tests:
    stage: test
    script: 
        - javac --release 14 -encoding utf8 -cp .:src/tests/junit-4.12.jar:src/ src/tests/testGame.java
        - cd src
        - java -cp .:tests/junit-4.12.jar:tests/hamcrest-core-1.3.jar:src/ org.junit.runner.JUnitCore tests.testGame


build_main:
    stage: test
    script: 
        - javac --release 14 -encoding utf8 -cp junit-4.12.jar:src/ src/Main.java
        